PROGRAM kind_parameter
IMPLICIT NONE
INTEGER(KIND=1)::i1
INTEGER(KIND=2)::i2
INTEGER(KIND=4)::i4
INTEGER(KIND=8)::i8
REAL(KIND=4)::r4
REAL(KIND=8)::r8
REAL(KIND=16)::r16
COMPLEX(KIND=4)::c4
COMPLEX(KIND=8)::c8
COMPLEX(KIND=16)::c16
LOGICAL(KIND=1)::l1
LOGICAL(KIND=2)::l2
LOGICAL(KIND=4)::l4
LOGICAL(KIND=8)::l8
CHARACTER(KIND=1)::ch1
CHARACTER(KIND=1,LEN=4)::ch2
PRINT*,'i1 size:',SIZEOF(i1)
PRINT*,'i2 size:',SIZEOF(i2)
PRINT*,'i4 size:',SIZEOF(i4)
PRINT*,'i8 size:',SIZEOF(i8)
PRINT*,'r4 size:',SIZEOF(r4)
PRINT*,'r8 size:',SIZEOF(r8)
PRINT*,'r16 size:',SIZEOF(r16)
PRINT*,'l1 size:',SIZEOF(l1)
PRINT*,'l2 size:',SIZEOF(l2)
PRINT*,'l4 size:',SIZEOF(l4)
PRINT*,'l8 size:',SIZEOF(l8)
PRINT*,'ch1 size:',SIZEOF(ch1)
PRINT*,'ch1,len=4 size:',SIZEOF(ch2)

END PROGRAM kind_parameter
