PROGRAM AOS_SOA
IMPLICIT NONE
INTEGER,PARAMETER::N=1000000,ITERMAX=100
INTEGER,PARAMETER::K=4
TYPE AOS
REAL(KIND=K)::X,Y,Z
END TYPE AOS

TYPE SOA
REAL(KIND=K)::X(N),Y(N),Z(N)
END TYPE SOA

TYPE(AOS)::P1(N)
TYPE(SOA)::P2
INTEGER::I,IT
INTEGER(KIND=8)::ST,ET,C_RATE
REAL(KIND=8)::DTIME1,DTIME2
REAL(KIND=K)::DIST2(N)
DO I=1,N
  CALL RANDOM_NUMBER(P1(I)%X)
  CALL RANDOM_NUMBER(P1(I)%Y)
  CALL RANDOM_NUMBER(P1(I)%Z)
  CALL RANDOM_NUMBER(P2%X(I))
  CALL RANDOM_NUMBER(P2%Y(I))
  CALL RANDOM_NUMBER(P2%Z(I))
END DO
CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITERMAX
  DO I=1,N
    DIST2(I)=(P1(I)%X)*(P1(I)%X)+(P1(I)%Y)*(P1(I)%Y)+(P1(I)%Z)*(P1(I)%Z)
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME1=(ET-ST)/DBLE(C_RATE)
PRINT*,DIST2(N)
CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITERMAX
  DO I=1,N
    DIST2(I)=(P2%X(I))*(P2%X(I))+(P2%Y(I))*(P2%Y(I))+(P2%Z(I))*(P2%Z(I))
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME2=(ET-ST)/DBLE(C_RATE)
PRINT*,DIST2(N)
PRINT*,'AOS:',DTIME1
PRINT*,'SOA:',DTIME2
PRINT*,'SoA/AoS(kind=',k,'):',DTIME1/DTIME2


END PROGRAM AOS_SOA
