PROGRAM COMEXP
IMPLICIT NONE
INTEGER,PARAMETER::N=10000000,ITERMAX=10
INTEGER::I,IT
INTEGER(KIND=8)::ST,ET,C_RATE
REAL(KIND=8)::DTIME
REAL(KIND=8),DIMENSION(N)::A,B
REAL(KIND=8)::X,Y,Z,R,TMP1,TMP2,TMP

CALL RANDOM_NUMBER(A)
CALL RANDOM_NUMBER(A)

CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITERMAX
  R=DBLE(IT)
  DO I=1,N
    X=R*SIN(A(I))*COS(B(I))
    Y=R*SIN(A(I))*SIN(B(I))
    Z=R*COS(B(I))
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Common_Exp(No Opt):',DTIME

CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITERMAX
  R=DBLE(IT)
  DO I=1,N
    TMP1=R*SIN(A(I));  TMP2=COS(B(I))
    X=TMP1*TMP2
    Y=TMP1*SIN(B(I))
    Z=TMP2*R
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Common_Exp(Opt):',DTIME



CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITERMAX
  X=1.0*IT;  Y=2.0*IT
  DO I=1,N
    A(I)=A(I)/SQRT(X*X+Y*Y)
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Code Motion(No Opt):',DTIME

CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITERMAX
  X=1.0*IT;   Y=2.0*IT
  TMP=1.0D0/SQRT(X*X+Y*Y)
  DO I=1,N
    A(I)=A(I)*TMP
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Code Motion(Opt):',DTIME

END PROGRAM COMEXP
