PROGRAM DEPENDENCY
IMPLICIT NONE
INTEGER,PARAMETER::N=1000000,ITMAX=1000
REAL(KIND=8),DIMENSION(N)::A,B,C
INTEGER(KIND=8)::ST,ET,C_RATE
REAL(KIND=8)::DTIME
INTEGER::I,IT
CALL RANDOM_NUMBER(A)
CALL RANDOM_NUMBER(B)
CALL RANDOM_NUMBER(C)

CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITMAX
DO I=2,N
  A(I) = A(I-1) + B(I)
END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,A(1)
PRINT*,'Flow Dependency(Elapsed Time)',DTIME

END PROGRAM DEPENDENCY
