PROGRAM CLUTTER2
IMPLICIT NONE
INTEGER,PARAMETER::N=10000
INTEGER::ITERMAX=10000
REAL(KIND=8),DIMENSION(N,N)::A,B
REAL(KIND=8),DIMENSION(N)::AA,BB
REAL(KIND=8)::C=12.5
INTEGER::I,J
INTEGER(KIND=8)::ST,ET,C_RATE
REAL(KIND=8)::DTIME

CALL RANDOM_NUMBER(A)
CALL RANDOM_NUMBER(B)
CALL RANDOM_NUMBER(AA)
CALL RANDOM_NUMBER(BB)

CALL SYSTEM_CLOCK(ST,C_RATE)
DO J=1,ITERMAX
  DO I=1,N
    IF(ITERMAX/=0) THEN
      AA(I)=AA(I)+BB(I)*C
    ELSE
      AA(I)=AA(I)-BB(I)*C
    END IF
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Loop Invariant condition(No Opt):',DTIME

CALL SYSTEM_CLOCK(ST,C_RATE)
!! TODO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Loop Invariant condition(Opt):',DTIME

CALL SYSTEM_CLOCK(ST,C_RATE)
DO J=1,N
  DO I=1,N
    IF(J<I)THEN
      A(I,J)=A(I,J)+B(I,J)*C
    ELSE
      A(I,J)=A(I,J)-B(I,J)*C
    ENDIF
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Loop Index dependent condition(No Opt):',DTIME

CALL SYSTEM_CLOCK(ST,C_RATE)
!! TODO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Loop Index dependent condition(Opt):',DTIME

END PROGRAM CLUTTER2
