PROGRAM ADDVEC
IMPLICIT NONE
INTEGER,PARAMETER::N=10000000,ITERMAX=100
REAL(KIND=8),DIMENSION(N)::A,B,C
INTEGER(KIND=8)::ST,ET,C_RATE
REAL(KIND=8)::DTIME
INTEGER::I,IT

CALL RANDOM_NUMBER(A)
CALL RANDOM_NUMBER(B)

CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITERMAX
  DO I=1,N
    C(I)=A(I)+B(I)
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,'Elapsed Time:',DTIME
PRINT*,C(1)

END PROGRAM ADDVEC
