PROGRAM MATMUL1
IMPLICIT NONE
INTEGER,PARAMETER::N=1024,NB=16
INTEGER::I,J,K,JB,IB,KB,IT
INTEGER(KIND=8)::ST,ET,C_RATE
REAL(KIND=8)::DTIME
REAL(KIND=8),DIMENSION(N,N)::A,B,C
REAL(KIND=8)::C0,C1,C2,C3,TMP

CALL RANDOM_NUMBER(A)
CALL RANDOM_NUMBER(B)
C=0.0

CALL SYSTEM_CLOCK(ST,C_RATE)
DO K=1,N
  DO J=1,N
    TMP=B(K,J)
    DO I=1,N
      C(I,J)=C(I,J)+A(I,K)*TMP
    END DO
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,C(1,1)
PRINT*,'InterChange(Opt):',DTIME

C=0.0
CALL SYSTEM_CLOCK(ST,C_RATE)
DO KB=1,N,NB
  DO JB=1,N,NB
    DO IB=1,N,NB
      DO K=KB,MIN(N,KB+NB-1)
        DO J=JB,MIN(N,JB+NB-1)
          TMP=B(K,J)
          DO I=IB,MIN(N,IB+NB-1)
            C(I,J)=C(I,J)+A(I,K)*TMP
          END DO
        END DO
      END DO
    END DO
  END DO
END DO     

CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,C(1,1)
PRINT*,'Blocking(Opt):',DTIME

END PROGRAM MATMUL1
