PROGRAM MAKEINPUT
IMPLICIT NONE
REAL::A(16,16), B(16)
CALL RANDOM_NUMBER(A)
CALL RANDOM_NUMBER(b)
OPEN(10,FILE='a.dat',STATUS='REPLACE')
WRITE(10,*) A
CLOSE(10)
OPEN(10,FILE='b.dat',STATUS='REPLACE')
WRITE(10,*)B
CLOSE(10)
END PROGRAM MAKEINPUT
