PROGRAM UNROLLING
IMPLICIT NONE
INTEGER,PARAMETER::N=1000000, itermax=1000
INTEGER::IT,I
REAL,PARAMETER::COEFF=0.125
REAL,DIMENSION(N)::A,B,C
REAL(KIND=8)::FLOPS,DTIME
INTEGER(KIND=8)::ST,ET,C_RATE

CALL RANDOM_NUMBER(B)
CALL RANDOM_NUMBER(C)

CALL SYSTEM_CLOCK(ST,C_RATE)
DO IT=1,ITERMAX
  DO I=1,N
    A(I)=B(I)+COEFF*C(I)
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
FLOPS=(1.0E-6*ITERMAX*2*N)/DTIME
WRITE(*,100) DTIME
WRITE(*,200) FLOPS
WRITE(*,*)A(1),B(1),C(1)

100 FORMAT("loop time = ",f12.5," seconds")
200 FORMAT("loop runs at ",f15.5," MFLOPS")
END PROGRAM UNROLLING
