PROGRAM MATMUL1
IMPLICIT NONE
INTEGER,PARAMETER::N=1024
INTEGER::I,J,K
INTEGER(KIND=8)::ST,ET,C_RATE
REAL(KIND=8)::DTIME
REAL(KIND=8),DIMENSION(N,N)::A,B,C
REAL(KIND=8)::C0,C1,C2,C3,TMP

CALL RANDOM_NUMBER(A)
CALL RANDOM_NUMBER(B)
C=0.0

CALL SYSTEM_CLOCK(ST,C_RATE)
DO J=1,N
  DO I=1,N-3,4
    C0=0.0D0;   C1=0.0D0;  C2=0.0D0;   C3=0.0D0
    DO K=1,N
      TMP=B(K,J)
      C0=C0+A(I,K)*TMP
      C1=C1+A(I+1,K)*TMP
      C2=C2+A(I+2,K)*TMP
      C3=C3+A(I+3,K)*TMP
    END DO
    C(I,J)=C(I,J)+C0
    C(I+1,J)=C(I+1,J)+C1
    C(I+2,J)=C(I+2,J)+C2
    C(I+3,J)=C(I+3,J)+C3
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,C(1,1)
PRINT*,'Unrolling(Opt):',DTIME

C=0.0
CALL SYSTEM_CLOCK(ST,C_RATE)
DO K=1,N
  DO J=1,N
    TMP=B(K,J)
    DO I=1,N
      C(I,J)=C(I,J)+A(I,K)*TMP
    END DO
  END DO
END DO
CALL SYSTEM_CLOCK(ET)
DTIME=(ET-ST)/DBLE(C_RATE)
PRINT*,C(1,1)
PRINT*,'InterChange(Opt):',DTIME
END PROGRAM MATMUL1
