PROGRAM TIMING
IMPLICIT NONE
INTEGER,PARAMETER::N=10000
INTEGER::I,J
INTEGER(KIND=8)::STIME, ETIME, C_RATE
REAL::STIME1,ETIME1
CALL SYSTEM_CLOCK(STIME,C_RATE)
CALL SLEEP(1)
CALL SYSTEM_CLOCK(ETIME)
PRINT*,'SYSTEM_CLOCK:',&
       (ETIME-STIME)/DBLE(C_RATE)

CALL CPU_TIME(STIME1)
CALL SLEEP(1)
CALL CPU_TIME(ETIME1)
PRINT*,'CPU_TIME:',(ETIME1-STIME1)
END PROGRAM TIMING

